version: "3.9"
services:
    test:
      image: "exercise-7"
      volumes:
        - .:/app
      command: python3 -m pytest
    run:
      image: "exercise-7"
      volumes:
        - .:/app
        - ./log4j2.properties:/spark/conf/log4j2.properties
      command: /spark/bin/spark-submit main.py